const NEEDED_KNIGHTS_LIST = [
	[2,3,2,3,3],
	[2,3,2,3,3],
	[2,3,2,3,3],
	[2,3,2,3,3],
	[2,3,2,3,3],
	[2,3,2,3,3],
	[2,3,4,3,4],
	[2,3,3,4,4],
	[3,4,4,5,5],
	[3,4,4,5,5],
	[3,4,4,5,5]
]

const ROLE_LIST = [0,1,2,3,4,
	["梅林","好人","好人","刺客","壞人"],
	["梅林","好人","好人","好人","刺客","壞人"],
	["梅林","好人","好人","好人","刺客","壞人","壞人"],
	["梅林","好人","好人","好人","好人","刺客","壞人","壞人"],
	["梅林","好人","好人","好人","好人","好人","刺客","壞人","壞人"],
	["梅林","好人","好人","好人","好人","好人","刺客","壞人","壞人","壞人"]
]

const NEEDED_FAILED_LIST = [
	[1,1,1,1,1],
	[1,1,1,1,1],
	[1,1,1,1,1],
	[1,1,1,1,1],
	[1,1,1,1,1],
	[1,1,1,1,1],
	[1,1,1,1,1],
	[1,1,1,2,1],
	[1,1,1,2,1],
	[1,1,1,2,1],
	[1,1,1,2,1]
]

const STATUS_BEFORE_INIT = 'FSM/STATUS_BEFORE_INIT';
const STATUS_INIT = 'FSM/STATUS_INIT';
const STATUS_TEAM_BUILD = 'FSM/STATUS_TEAM_BUILD';
const STATUS_TEAM_VOTING = 'FSM/STATUS_TEAM_VOTING';
const STATUS_TEAM_VOTED = 'FSM/STATUS_TEAM_VOTED';
const STATUS_MISSION = 'FSM/STATUS_MISSION';
const STATUS_MISSION_FINISHED = 'FSM/STATUS_MISSION_FINISHED';
const STATUS_GAMEOVER_SUCCESS = 'FSM/STATUS_GAMEOVER_SUCCESS';
const STATUS_GAMEOVER_FAIL = 'FSM/STATUS_GAMEOVER_FAIL';
const STATUS_ASSASSIN = 'FSM/STATUS_ASSASSIN';
const ACTION_INIT_GAME = 'FSM/ACTION_INIT_GAME';
const	ACTION_START_ROUND = 'FSM/ACTION_START_ROUND';
const	ACTION_BUILD_TEAM = 'FSM/ACTION_BUILD_TEAM';
const	ACTION_VOTE = 'FSM/ACTION_VOTE';
const	ACTION_DRAW_VOTES_RESULT = 'FSM/ACTION_DRAW_VOTES_RESULT';
const	ACTION_EXECUTE_MISSION = 'FSM/ACTION_EXECUTE_MISSION';
const	ACTION_DRAW_MISSIONS_RESULT = 'FSM/ACTION_DRAW_MISSIONS_RESULT';
const	ACTION_ASSASSINATE = 'FSM/ACTION_ASSASSINATE';

const INIT_MISSION_RESULTS = [];
const INIT_FAIL_VOTES = 0;
const INIT_CAPTAIN = -1;
const INIT_ASSASSINATED = -1;
const INIT_GODDESS_RESULTS = [];

module.exports = {
	NEEDED_FAILED_LIST,
	NEEDED_KNIGHTS_LIST,
	ROLE_LIST,
	STATUS_BEFORE_INIT,
	STATUS_INIT,
	STATUS_TEAM_BUILD,
	STATUS_TEAM_VOTING,
	STATUS_TEAM_VOTED,
	STATUS_MISSION,
	STATUS_MISSION_FINISHED,
	STATUS_GAMEOVER_SUCCESS,
	STATUS_GAMEOVER_FAIL,
	STATUS_ASSASSIN,
	ACTION_INIT_GAME,
	ACTION_START_ROUND,
	ACTION_BUILD_TEAM,
	ACTION_VOTE,
	ACTION_DRAW_VOTES_RESULT,
	ACTION_EXECUTE_MISSION,
	ACTION_DRAW_MISSIONS_RESULT,
	ACTION_ASSASSINATE,
	INIT_MISSION_RESULTS,
	INIT_FAIL_VOTES,
	INIT_CAPTAIN,
	INIT_ASSASSINATED,
	INIT_GODDESS_RESULTS
}